name: CustomPlugin
version: 1.0
main: me.chisdealhd.customplugin.ChisdealHDPlugin
author: ChisdealHD
description: Custom Test
 
commands:
  test:
    usage: /<command>
    description: Nothing see here
  online:
    usage: /<command> [online|reload] [message]
    description: Twitch Test
    aliases: [tw]